CREATE TABLE USER (
	IDX BIGINT(5) NOT NULL AUTO_INCREMENT
	, ID VARCHAR(50) NOT NULL
	, PASSWORD VARCHAR(50) NOT NULL
	, PRIMARY KEY(ID)
);

CREATE TABLE BOARD (
	IDX BIGINT(5) NOT NULL AUTO_INCREMENT
	, TITLE VARCHAR(100)
	, WRITER VARCHAR(50) NOT NULL
	, CONTENT TEXT
	, PRIMARY KEY(IDX)
);